import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/client-user/header/header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Demo Blog App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header />
                {children}
            </body>
        </html>
    );
}
